#!/bin/bash

#### Begin script ####

### Finding drivers using relative path and cd to main directory ###
## See http://stackoverflow.com/questions/24112727/shell-relative-paths-based-on-file-location-instead-of-current-working-directory
## I DON'T THINK THIS WILL WORK WHEN SCRIPT IS MOVED UP

parent_path=$( cd "$(dirname "${BASH_SOURCE}")" ; pwd -P )
cd "$parent_path"
cd ..

### Initialize testReport.html ###
## sed info - http://unix.stackexchange.com/questions/121161/how-to-insert-text-after-a-certain-string-in-a-file
## datestamp - http://stackoverflow.com/questions/8228047/adding-timestamp-to-a-filename-with-mv-in-bash

DATE=$(date +"-%Y-%m-%d")
printf "<link rel='stylesheet' type='text/css' href='../docs/style.css'>" > reports/report$DATE.html
sed -i '1 i<head>' reports/report$DATE.html
sed -i '3 i</head>' reports/report$DATE.html
printf "Team TBD Testing Report\n" >> reports/report$DATE.html
DATE2=$(date +"%m-%d-%Y")
printf "Generated by $USER on $DATE2" >> reports/report$DATE.html
sed -i '5 i<html>' reports/report$DATE.html
sed -i '$ a</html>' reports/report$DATE.html

### Compile drivers ###
## Make these into .jar executables later so no need to javac?
## -cp - http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/classpath.html
## -cp - http://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java

javac -cp "./project/src:./oracles" testCasesExecutables/*.java

### Run testCases (command line args is testCase.txt) and add to report with sed ###
## See http://stackoverflow.com/questions/10523415/bash-script-to-execute-command-on-all-files-in-directory

cd testCasesExecutables
for file in ../testCases/*
do
	echo -e "<div class="container">" >> ../reports/report$DATE.html
	java -cp "..:./:../oracles" testCaseMono "$file" >> ../reports/report$DATE.html
	echo -e "</div>" >> ../reports/report$DATE.html
done
sed -i '$ a</html>' ../reports/report$DATE.html
sed -i '1~2a<p>' ../reports/report$DATE.html
sed -i '2~1a</p>' ../reports/report$DATE.html

### Display report.html in browser ###

if which xdg-open > /dev/null
then
  xdg-open "../reports/report$DATE.html" 
elif which gnome-open > /dev/null
then
  gnome-open URL
fi
